<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>outOfStock</name>
   <tag></tag>
   <elementGuidId>727bde75-cf95-4610-b959-c2e88a334dde</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[3]/div[2]/div[3]/div/div[1]/form/div/div/div/div/div/div/span[4]/div/div/ul/li[3]/a/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[3]/div[2]/div[3]/div/div[1]/form/div/div/div/div/div/div/span[4]/div/div/ul/li[3]/a/label</value>
   </webElementProperties>
</WebElementEntity>
