<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icon_info</name>
   <tag></tag>
   <elementGuidId>53fa350e-31d5-4366-b656-71bf7bf69dfc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tab-select-plan > div.message-box-desc > div.home-message-desc > div.question-info > a > i.fa.fa-question-circle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tab-select-plan']/div/div[2]/div/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-question-circle</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-select-plan&quot;)/div[@class=&quot;message-box-desc&quot;]/div[@class=&quot;home-message-desc&quot;]/div[@class=&quot;question-info&quot;]/a[1]/i[@class=&quot;fa fa-question-circle&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-select-plan']/div/div[2]/div/a/i</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div[2]/div/a/i</value>
   </webElementXpaths>
</WebElementEntity>
