<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>pickup2</name>
   <tag></tag>
   <elementGuidId>7153210d-fbc3-4da1-86a0-32e28faff60e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[4]/div[1]/div/div/div[1]/div/div[2]/div/div/ul/li[6]/div[2]/div/div/div[1]/div/div/div[2]/div[2]/div/div[2]/label/span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[4]/div[1]/div/div/div[1]/div/div[2]/div/div/ul/li[6]/div[2]/div/div/div[1]/div/div/div[2]/div[2]/div/div[2]/label/span[1]</value>
   </webElementProperties>
</WebElementEntity>
