<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>202f4fa4-0afc-4ac8-ba17-2ea09dde9970</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/user/profile-image-58276-rnpcxmpxhz.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;buyer_inbox_tab&quot;)/div[@class=&quot;tab-pane fade-in&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;chatdmbinbxpg-listmsg&quot;]/div[@class=&quot;chatdmbinbxpg-ind-sec&quot;]/div[@class=&quot;chatdmbinbxpg-ind-tbl&quot;]/div[@class=&quot;chatdmbinbxpg-col-prf&quot;]/img[1]</value>
   </webElementProperties>
</WebElementEntity>
