<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_cat6</name>
   <tag></tag>
   <elementGuidId>0f366c23-c2ae-452b-8f88-b256abd9cfb6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;add-item-area&quot;]/div/div[1]/div/div/div/div/div/div/div[2]/div/div/div[2]/ul/li[6]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;add-item-area&quot;]/div/div[1]/div/div/div/div/div/div/div[2]/div/div/div[2]/ul/li[6]/label</value>
   </webElementProperties>
</WebElementEntity>
