<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textlabel__AvrItemsSoldPerOrder</name>
   <tag></tag>
   <elementGuidId>38fa7bf2-c58e-4024-9895-82b7d358a54a</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Avr Items Sold Per Order</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react_0HLQLNIB1HDC0&quot;)/div[1]/div[@class=&quot;dashboard-container&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;dashboard-content&quot;]/div[@class=&quot;dashboard-board&quot;]/ul[1]/li[@class=&quot;average-sold&quot;]/p[1]</value>
   </webElementProperties>
</WebElementEntity>
