<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>value_serviceDesc</name>
   <tag></tag>
   <elementGuidId>1208b738-058b-4e72-baac-fbb0086a0187</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;items-list&quot;)/div[@class=&quot;item-box item-box-size col-md-3 col-sm-4 col-xs-6&quot;]/div[@class=&quot;item-box-inner&quot;]/div[@class=&quot;item-box-bottom&quot;]/div[@class=&quot;item-fix-table&quot;]/div[@class=&quot;item-sec-cat-name&quot;][count(. | //*[@class = 'item-sec-cat-name' and (text() = 'test_name_please_ignore' or . = 'test_name_please_ignore')]) = count(//*[@class = 'item-sec-cat-name' and (text() = 'test_name_please_ignore' or . = 'test_name_please_ignore')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>item-sec-cat-name</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>test_name_please_ignore</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;items-list&quot;)/div[@class=&quot;item-box item-box-size col-md-3 col-sm-4 col-xs-6&quot;]/div[@class=&quot;item-box-inner&quot;]/div[@class=&quot;item-box-bottom&quot;]/div[@class=&quot;item-fix-table&quot;]/div[@class=&quot;item-sec-cat-name&quot;]</value>
   </webElementProperties>
</WebElementEntity>
