<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>category 99</name>
   <tag></tag>
   <elementGuidId>9ea0f827-cadf-4d80-9a0c-d2ed29319024</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[4]/div[2]/div/div/form/div/div[1]/div/div/div/div/div/div[2]/div/div/div[2]/ul/li[9]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[4]/div[2]/div/div/form/div/div[1]/div/div/div/div/div/div[2]/div/div/div[2]/ul/li[9]/label</value>
   </webElementProperties>
</WebElementEntity>
