<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_goToMessage</name>
   <tag></tag>
   <elementGuidId>09ca85bd-b3eb-485a-9bbf-8e9a983f9933</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-right-gray-arrow</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;seller_inbox_tab&quot;)/div[@class=&quot;tab-pane fade-in active&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;chatdmbinbxpg-listmsg&quot;]/div[@class=&quot;chatdmbinbxpg-ind-sec&quot;]/div[@class=&quot;chatdmbinbxpg-ind-tbl&quot;]/div[@class=&quot;chatdmbinbxpg-col-act&quot;]/a[1]/i[@class=&quot;icon-right-gray-arrow&quot;]</value>
   </webElementProperties>
</WebElementEntity>
