<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>CheckoutbyUnit</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>07af9d86-25cf-48b4-bfae-bc34f8955ac3</testSuiteGuid>
   <testCaseLink>
      <guid>e18df10e-19d9-4a72-8949-1b25605892a3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Utilities/CONSUMER/Consumer Login Non Private</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>6139accb-46a1-4495-b991-8c1b3ae2b8fa</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CONSUMER/SPACETIME/Checkout Scenarios/Checkout by Unit/01_ServicePerHour247</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aaf726e7-920d-4fae-94d9-1114bbe617db</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e2e00957-c490-42fe-bfd8-3bb44f6683da</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a1544adc-56a1-4095-a3a9-7ab2bf152d1f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1caeb7b3-f465-4635-9c1c-31c0f8cf41c6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dc013a5b-4f6f-4ec7-a0f2-45485bcda8c2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94a093e1-ea6a-471b-b611-0be60f6c0e89</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cd51375a-96d7-4004-8c51-9f6253080c60</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1596b5d0-26e8-439e-8c19-b903b9380493</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CONSUMER/SPACETIME/Checkout Scenarios/Checkout by Unit/02_ServicePerDay247</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3a02ee10-f071-440c-ae65-397ccb71b0f6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ff05b42f-c5f2-46c1-b741-df373ea84c10</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>91ff19c4-39db-42e5-97c5-9174dc85b93c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>44b7e984-f653-4ba2-a1d2-9ff5e81d0e76</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b92c0a84-93d6-4954-b147-29ad8d1ce7d0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>272df48a-13ae-414d-9455-6a680c4a8fb8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae01f5bd-9494-473f-9c7c-2a49c8e93d0f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>adffc4f0-4cb0-4651-86ec-2cb3e26a5ee3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CONSUMER/SPACETIME/Checkout Scenarios/Checkout by Unit/03_ServicePerWeek247</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e94ec64e-4d25-4aff-bc93-0c8444dc1f33</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d6c00110-004d-44bf-8bc8-c7794c0f5dab</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>78b9e09b-10e2-49d8-84c3-a1788354c178</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1fcd9bf3-93ec-42be-980a-1ed8c91cf7ec</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ac7b6e07-a929-4461-8ae6-d3bcb1a38a9d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ac73a144-81b0-4d39-a9c4-af4a886bed4f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b6ca6ffa-815a-4996-b8b1-126b4102d3da</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1243169c-3e32-49fb-b7ee-1764ddf1bfbb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CONSUMER/SPACETIME/Checkout Scenarios/Checkout by Unit/04_ServicePerMonth247</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>68accc38-5ae4-4e11-8bd6-54d75e8d911b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1c0dce07-6e15-407d-86db-96c2371edae0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>83354fdf-e842-4421-b0a3-0caee5a523db</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>17398b81-eac7-45ec-9c59-638d29dd1322</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dd272d43-b103-46dc-831f-3ca53fad5aa5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>be9888a0-fe7a-4910-8352-db8de00cb35c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>be42fc0c-fd67-4788-999c-12826ff80574</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cef7571c-0969-451a-9cf2-e7bfa2ca2c36</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CONSUMER/SPACETIME/Checkout Scenarios/Checkout by Unit/05_ServiceCustomPer15min247</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b6438c51-d088-40e0-b628-b0d3a8996654</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3e6493b6-a010-447f-95af-2d0a851e9a15</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>39944733-7f7e-49b2-8b85-e56180e8e9c3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>62dcd95c-f674-468a-9032-54cd0a821e8f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b3e210c1-6deb-42a1-a411-7eaf182aa2b2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e49c6a02-7436-4871-94d6-a05e26c81de6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0fb55e95-da8c-476e-af0d-e3f70ab1b828</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>dc460574-7808-4827-82de-317d6c19fa89</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CONSUMER/SPACETIME/Checkout Scenarios/Checkout by Unit/06_ServiceCustomPer150min247</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a2b2f99a-00e4-4ea3-a046-0a7da6b15ad9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f3fd7599-48dd-400a-9007-7361238b57c2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1217eaa4-b9a2-4220-82fc-2ce6b2c81d2c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>13c4f469-3dec-44f4-ae09-70ef9c916bb2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e4c8bc0d-4784-48ff-85a7-b5a175f6d7a7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b41f485c-2430-4622-83e1-0559168f2847</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8c3a5580-fe0d-4641-a331-e8f7dd7a5374</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b8a6557c-0b63-47a7-871d-1537e1cd9034</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CONSUMER/SPACETIME/Checkout Scenarios/Checkout by Unit/07_ServiceCustomPer1hour247</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>be85507c-dbfe-41cf-90bb-9488130a045a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>75d78949-2ac5-4475-9e9e-ea4ff982e680</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7c1709a5-f0ad-4229-92d2-9f293d009d13</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>43c68fc4-5152-402a-9e69-b7bd373f1c7c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d591ac4a-c7c6-44d6-b905-18539e923c2a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f27fec07-0157-430e-b8ae-b25715fe6cde</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>24c33d4b-0785-4d62-9015-1cfe139c74f3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8988aa27-acdb-4f06-b929-8db3a10d559e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CONSUMER/SPACETIME/Checkout Scenarios/Checkout by Unit/08_ServiceCustomPer23hrs247</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>631922a8-2676-44b2-9bde-43dbe41da058</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e4f73476-990a-439d-8fe5-2ad78675d1c3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>216f8819-2e6d-488d-bae3-48ed358d83d2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b6826afc-8895-4344-b4ed-029335f0a1be</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4c17083f-579b-4352-9d9c-4cbb0202595b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7a59ea82-60e4-40e9-abbc-506974c0301e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>14624670-ac96-4367-8d79-21da63cc17b2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8fc02467-caeb-43f1-814c-bff9e0a5b2d8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CONSUMER/SPACETIME/Checkout Scenarios/Checkout by Unit/09_ServiceCustomPer1Day247</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>07505a1b-ef44-4737-96bf-c43283e08dd9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>561599f2-496c-424f-ac15-e57d63ac5f6d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bc7f37b0-6214-4a54-bf75-6314acaa1230</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2a893665-760c-41c8-8ec9-05745af193fe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0c069ce0-d66f-4373-9d32-c16ba8fd344b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6d8b1b3e-94ee-4f62-a2c3-2a0c4468a61f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a080c521-59a1-413b-8c1d-3ba6dabc818d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0dd5efff-7ed8-4aaf-97ea-3dc84b8d1fa1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CONSUMER/SPACETIME/Checkout Scenarios/Checkout by Unit/10_ServiceCustomPer28Day247</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4b933047-db78-49af-b1cc-16b4e2d3f225</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4a368f5f-5e5f-4876-b207-7c8c7262d5bf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f70440ed-07cf-4d02-a997-8e9063d0cd25</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6c60a5ec-6f27-40fb-ab91-efb50ab6ea7d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>18fc67f0-68b6-429a-8f4d-74585b18a8e6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2ad6c4e0-90d3-46a7-84c5-a9d1e2a92faa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>54934969-1207-4fab-85b8-b5f2c464aa05</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f8f30121-6096-48e4-b906-f0d1560bbe0d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CONSUMER/SPACETIME/Checkout Scenarios/Checkout by Unit/11_ServicePerHourNot247</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0cf41149-a66c-495a-9361-91d3d35a4f64</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b8c536f1-da14-4616-8eca-ba8552c302cc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e79b02a9-d428-4904-aa1e-3841cdc2e8e3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>56902422-eda7-4faf-961c-188fd25867f2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>399d899f-f38e-477e-9df9-72b4fae39943</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f7f04203-b9e7-4845-ae3f-c0df1a3eeaec</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2fd50012-8ad1-4d6b-aa27-c33b83c22937</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d74c8b8b-3c3b-4e6d-a9fa-5273bee2b2da</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CONSUMER/SPACETIME/Checkout Scenarios/Checkout by Unit/12_ServicePerDayNot247</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d964877-ee46-4076-9750-fad1ca9540de</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8726b796-b453-4e2c-998c-147922552067</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fa4c7840-eab7-4f0a-a9ec-516f93f87912</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>940bd5d9-b2e6-44bd-8508-97a7fe88b7c3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fb249054-6c70-4e1c-a8ea-86830ffff065</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>41a89448-c8f1-47fb-bf56-217f4d4c238b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a1cd8e52-7dd7-4d61-8a8a-d98de3986edb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d6b70f72-7e1a-42ee-98c9-8398d77d54b0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CONSUMER/SPACETIME/Checkout Scenarios/Checkout by Unit/13_ServicePerWeekNot247</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c20d1ea9-d4ed-455d-870e-266f7cc16756</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e4d4bb60-5948-450c-8d7e-74d5acb5da0b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cdf7b996-93f3-4c89-816c-2ea652c730b5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d92f02d0-0b0c-433b-8b1e-bf888b35a1b8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bf913289-8aa1-4323-af89-bb779425ec46</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b7e0b9ba-c56b-4c5b-b148-4e4152570a33</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c63fc6cd-cd73-431a-b0ea-a25380a49c2d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>66047812-1ef6-4553-bfb8-edc2f890b630</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CONSUMER/SPACETIME/Checkout Scenarios/Checkout by Unit/14_ServicePerMonthNot247</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>daefa6a4-e67b-4a1d-ba71-18cc7b639250</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>31e6331d-2215-4496-a5d5-da86a363d593</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ee261f9-62f2-43fb-84ad-e0ebe72ebdbd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6c974f45-b685-443f-8ae9-8458727ba7c1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ac637b75-95f9-4ee0-83a2-53d4db2c1809</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e92a1916-1405-4bac-8bac-d39d8fa6e3c1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f243edac-673a-4229-afb7-e83f7963b519</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5fcd124b-3e4b-45ef-8269-9a27b92dd77e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CONSUMER/SPACETIME/Checkout Scenarios/Checkout by Unit/15_ServiceCustomPer15minNot247</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>89ea4758-4591-44c4-99e2-6c2598553fe2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b8f78c02-f1a6-4ad4-a224-9b3fc45d9280</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ccbfbdc1-a425-47c0-b04a-980da9b135a7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7a0b5064-f41b-41a5-9b3c-c1a6adfbea90</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bf3e675a-313c-48a5-b6a1-78b2717e640e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>461e967a-5665-4625-b3ce-4511c97974c1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c04538c3-930d-49b7-96db-6dd5dd94bede</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>92e0ebb5-fb6b-4be8-b6f4-860280a261b8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CONSUMER/SPACETIME/Checkout Scenarios/Checkout by Unit/16_ServiceCustomPer150minNot247</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1cc26e49-8c3b-449d-b039-ca9cd3acd9ea</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b3e8c972-f24c-48ae-bd56-1502b142d196</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ccfdacce-068a-48fa-b0ac-954d47de8aa7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4503f6ec-3784-4a59-b960-597aad072c9d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d8f14481-20b4-450e-b76c-1444edc3bad0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2682ac2b-c844-41d8-b991-5ea2486cfbd0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>67833945-d56f-4091-8df8-65b38a8c0d4a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a983d1b4-ef00-4343-a312-c73236b457b9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CONSUMER/SPACETIME/Checkout Scenarios/Checkout by Unit/17_ServiceCustomPer1hourNot247</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>85051399-5f84-4699-b0e6-da160b0da202</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0f326db3-134b-4819-b164-03fcf354168c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ba20d018-290d-4288-82f0-4f40286c12cb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7b638ef5-52a7-41e4-a967-2111afa39c66</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b2ec9aea-f951-4d77-8221-6a09cb6df5e2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8b4f9350-fc28-41b5-82de-6fa19375b554</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9eb9b63a-b25e-46f8-b853-5f0f89fc70f4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>596740a5-8172-47fd-b8a9-361944d109e2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CONSUMER/SPACETIME/Checkout Scenarios/Checkout by Unit/18_ServiceCustomPer1DayNot247</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a6f264c-a241-467c-8c80-b82b493e0f57</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ff90ec95-3b76-4bda-9a81-d78801f633d8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7f68aa48-c4ca-49ea-a547-4a4e20d73544</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ac9ec5d4-76c6-42b8-ab49-f5313aa906da</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>55d71172-8aaf-44aa-ab22-7da7cef09828</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>caaec14d-80e9-4597-9661-576747a81227</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>668ece82-08d4-414d-9eca-13ac4f347062</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>15771f35-4c5a-4626-b7d1-07af2210b9f2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CONSUMER/SPACETIME/Checkout Scenarios/Checkout by Unit/19_ServiceOvernight</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d81225a6-d732-4c86-a2c0-7c55c5807847</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e3a3f97e-86c5-4f82-bd0d-aa863b1642ea</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5f9f41ad-af6f-4eca-ac33-434050063a95</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a0906b47-5e77-4790-8a6a-0e4efca01c7d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>adb917d1-d8bf-4026-802a-ceeb202298a0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bf5acb20-8dd7-4b3a-8e66-9cbfee9fb5b2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ba6a0a66-5bad-49fb-add7-dbcc3b92ecdf</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c03510c5-6a96-474c-973c-7ff4f1396491</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CONSUMER/SPACETIME/Checkout Scenarios/Checkout by Unit/20_ServiceOvernighPerWeek</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e6f8555e-a687-4fe5-9e0f-707ba2710c73</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab6eaf93-0f4e-47ef-a21a-f76085ee5313</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>61159861-a3d8-4931-814d-28011defae2a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>97a0c4ef-b15a-4757-8320-9ce7df0c94b9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>68a42abd-d894-484e-932d-486a16c8f5ed</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d3f599b7-06f2-424f-82eb-c82fc2e20178</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e3722fa4-4bb6-41c8-9711-418800afe5da</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5e90bac7-273e-4f78-899a-79759df4bf38</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CONSUMER/SPACETIME/Checkout Scenarios/Checkout by Unit/21_ServiceOvernightPerMonth</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2e08265a-7c12-41d1-becd-5f606e123ec8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1417fe11-4155-492e-b782-c83717dd8638</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e43d49a5-e244-46ee-984b-f082f76e01b5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>48b8e134-82c0-4779-be21-f2e7fbcb119c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d723a58f-bd53-4cc4-88de-92ddeff8a54c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>54d4cd25-d371-4c00-a7f4-22205ea52315</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>df100515-5ac0-401f-acab-37be7286bcbd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d719a9ca-322a-408a-8687-eda2064737af</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CONSUMER/SPACETIME/Checkout Scenarios/Checkout by Unit/22_ServiceOvernightPer1Night</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c274964c-0962-4d70-90bc-4a0df1ae9527</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0d693ad0-1b6e-48fa-b0c7-f6769bc3ecdd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dcbdaf12-2dd3-4746-b810-d2bde95c181b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4ea8346d-4480-418f-886d-0165a72a4cde</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>332f340c-f6f3-49ac-9a23-6fee7b31c04c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ff578f6a-c6c8-4f34-b2af-b44c7430ec46</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>68958434-d1bb-4def-bedd-61dd12001128</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a64ea2ac-3ce1-4186-8c72-d1e2972a13f7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CONSUMER/SPACETIME/Checkout Scenarios/Checkout by Unit/23_ServiceOvernightPer28Nights</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dc0677c6-fd53-4937-b245-eb5a25a6d9cd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dadc7a09-cc84-4ce6-b283-4ab1c2e39f6a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b89851fd-42d5-403f-b7d4-794fb61643d0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7e56b03f-0ede-49ac-bf90-948170c8ca41</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>08e22f07-e81d-4061-ac33-0f0a0881939f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1c313e9e-22d4-4c7c-b7c2-7c5f4ac177e1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7668377f-0445-4c89-a938-05fd882a0c92</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fab85d60-40fa-43f4-9c4b-9fc328019e06</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Utilities/MERCHANT/Logout</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
