<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>CheckoutbyUnitDuration</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>c66c00f0-b26c-4b4f-91f7-b3c87b781f9b</testSuiteGuid>
   <testCaseLink>
      <guid>5b5477f5-7423-42df-96d7-9fb0de26203a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Utilities/CONSUMER/Consumer Login Non Private</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>7881a489-3df7-49e7-8fdc-c926e74038ab</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CONSUMER/SPACETIME/Checkout Scenarios/Checkout by Unit and Duration/01_ServicePerHour247</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f432859d-02c0-4b72-9d50-2559fc00ed37</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c714c9f2-6092-4549-a5c2-a7765a2306e3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e824badd-354d-4ff3-858a-a22234c0bf53</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6d22eab6-6ca0-41bc-a190-5b6b19985ece</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2f4484fd-614c-4b0a-ad2d-e16d0048bac7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>48fb466b-fba4-478e-8ecc-6672b3a4669c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f56fe24f-8fba-4b5c-b48a-cabed0e704af</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ac94b380-765b-44ca-b67b-2698b530f5ab</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/CONSUMER/SPACETIME/Checkout Scenarios/Checkout by Unit and Duration/02_ServicePerDay247</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>18c7e1c4-72f2-4ac1-a0e7-cd83c6bce7f9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>38c2b712-ae6a-430a-b7b3-375442e1f3ef</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5758915c-fce3-45cd-a981-9e531ce7e8f2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>89553226-9d58-49fc-976b-28e25754e362</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7aadc35e-49be-4a64-a7ba-bf6cfb7c8633</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8df21047-1390-44b2-98f8-67058ce04da3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2aef98a6-a540-45b5-84b3-216e48ba3639</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e4a3f5af-6ca4-4631-9b65-d4fc718c9beb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/CONSUMER/SPACETIME/Checkout Scenarios/Checkout by Unit and Duration/03_ServicePerWeek247</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a1829d69-dd30-47ad-aa09-f308107049d8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9e6cfc98-4f58-4d45-affb-a0ba2a1d5709</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>521d8f80-7e11-4e51-a10d-c68dbbd70c99</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>022bb8be-1436-4df7-9d3d-87e3fb2cf9b2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>294d88c5-5297-487f-84ab-a7bb9dde474d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>78941d92-3b7a-4b37-9760-2a434a87643c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>30476a1c-4463-4069-8a8a-00686615ac37</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cc1ff3c3-01cf-4f63-a8f9-50b7de5442bb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/CONSUMER/SPACETIME/Checkout Scenarios/Checkout by Unit and Duration/04_ServicePerMonth247</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dc175ebf-53e9-4dcd-be04-18a162fff285</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>265219cf-43d2-4066-908e-58e53ba21b0f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bda9b781-7c45-407c-b15e-15f029237fdd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c7525415-1062-4cfe-b8d0-d1fe0b24bb4a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fb949528-2a16-4204-b48b-fce7f6ac9515</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e05fa700-17de-4d3c-ab9b-ba2ce74de0ce</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5c3ea90f-53cb-49ca-a480-ea62137fc26b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cb54829d-fe15-49e8-8801-d7784a1788fd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/CONSUMER/SPACETIME/Checkout Scenarios/Checkout by Unit and Duration/05_ServiceCustomPer15min247</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2b137998-fbd9-4255-af2f-f8f8fbc1e6c8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2ae79a17-9cc0-415f-b62f-96d6a0b0fb60</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>93769b25-547e-47ea-b38f-643a2f72591d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1fe9471c-a697-44b6-81f0-521b53edd592</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f6949b7f-0209-4671-84f3-0983e8d3ab0f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1c3edd1e-6ebb-4a4f-9e91-2328d020fb01</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>42676b8c-5d1a-4363-8be9-179f2d7112b1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e3dfe9f3-3bc3-481f-8ee8-2778ddc66afc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/CONSUMER/SPACETIME/Checkout Scenarios/Checkout by Unit and Duration/06_ServiceCustomPer150min247</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a785d95c-22ae-400f-85b5-5f9c0352bcec</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>44c50c94-30a7-4a3c-a2a0-87c442cd8ea4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>208d9dcf-246e-43f1-8fec-88a6e07641db</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4a4295c1-306a-49ed-9f04-94bc814f2d97</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5e49b151-64ba-4a40-b14c-18712e3a0fa8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fc7e8e23-e7b8-4a31-a677-501b7bfe35a2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>446f180e-0da4-4249-b128-cb3c02cdc40a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f356e38a-e1b7-49e3-8723-0a48be75a1e3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/CONSUMER/SPACETIME/Checkout Scenarios/Checkout by Unit and Duration/07_ServiceCustomPer1hour247</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d4480371-1729-47a7-9917-7be5c3059451</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>11ab825a-ab53-4c39-a966-7a01647392ea</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6a9f018d-02b4-498b-b944-bdadff5fd450</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fae88765-0700-4348-bfec-95088d16cd21</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5982a729-4253-410e-a434-a55bbe75b769</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e52c1b06-b208-4e70-88fc-926f0eb91f68</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>91339d16-73de-479f-88ea-c23d458cff95</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>62590c23-3aeb-4d9a-b95f-1cfdf0c20b0a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/CONSUMER/SPACETIME/Checkout Scenarios/Checkout by Unit and Duration/08_ServiceCustomPer23hrs247</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b2b55597-f323-493a-8c60-4b1a533122ce</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3abb3bc4-e121-4df4-a7c8-bf3f49c608a5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>44d5998e-e2d9-4a96-8a15-532d09816d14</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>abbd4c18-cd19-442c-8e43-fe4d7c4cf8ce</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>67488e6a-8f99-4fea-8df0-faa75226ae83</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>970e17d4-ad2f-41ec-91d0-71ad8f715ee0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4f68bb31-c5bf-4fbc-ab60-8d7bf9036807</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>32cdf900-1d3d-4360-9095-4f1d951f5a2b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/CONSUMER/SPACETIME/Checkout Scenarios/Checkout by Unit and Duration/09_ServiceCustomPer1Day247</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>38d02e32-5679-4e6c-9cbb-f770f1a19833</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>69cc45c4-c491-4d7a-a336-315debd5fae3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1210a781-3798-4af6-8634-942e5772d82c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8f81cd7d-931b-49ec-95b3-8d77dbce043e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>434a0926-9061-45c5-9f12-ec9563221923</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a381d31e-e8c9-48e8-bed6-506451359700</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>88462ced-404e-4f24-a83c-091e6e85bd36</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cfd44707-333e-4db8-acb3-9b61aa0dc461</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/CONSUMER/SPACETIME/Checkout Scenarios/Checkout by Unit and Duration/10_ServiceCustomPer28Day247</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>948c5303-0b10-41ea-a93f-52bc36099d9d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fc511341-eae3-41b4-a0dc-26ebeba9c64a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2d109baa-f772-41b9-a9e2-828180a51c3b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>81e2cbea-8c5c-4d5d-9af0-6fa1beba3109</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4f4259bf-d541-4e58-b483-e214750de2fa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3e2bf5d4-b7f9-4542-be39-0f1ae894187b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>82f65f4a-d9db-43b3-a547-eaaae7e2d82d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>90f8b235-b4c6-4de5-a0ec-2decc9f29828</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/CONSUMER/SPACETIME/Checkout Scenarios/Checkout by Unit and Duration/11_ServicePerHourNot247</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>87344b87-b536-4eeb-b3da-12325a49cb16</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9893a086-7d6e-450c-a004-2a56d6d78207</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f694d39c-21ba-4434-9dcc-b73f18643885</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>258d4083-7c88-4645-9ac5-a364c56d99e7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5b8e32cc-5217-4a83-9763-ab9d282223d9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>99644f5d-4394-4941-94c3-e32df33b1fed</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e32ed176-0caf-470a-944c-ef034cc54ef7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>37f3a9db-f9c6-40d5-b8f7-66ed93abce53</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/CONSUMER/SPACETIME/Checkout Scenarios/Checkout by Unit and Duration/12_ServicePerDayNot247</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>11a81860-61e9-43af-a9e1-50572c0a1b62</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>24e35189-67c5-40ce-a142-dba55fd5bca4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9c736a96-817b-459a-a306-db00b171c8dd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>098898b6-3439-475a-b550-12f0b898ab46</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cc3d142a-6733-459b-a0e0-7396db3bbda0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7d9ce82a-fc5a-499e-854f-26d94e9a6907</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0a43a19e-d9ff-439d-98bd-fc43a2d1c0c1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2695db92-20e0-405d-8845-7ab8b65e8469</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/CONSUMER/SPACETIME/Checkout Scenarios/Checkout by Unit and Duration/13_ServicePerWeekNot247</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3608baf2-5959-4987-813b-649fd427fa70</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>69692606-8522-4097-b42c-aed164bac728</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8c2a34be-c0c2-4a1f-b7fb-5542674de0c1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>541f7b72-b76a-4eff-bd7c-641a47fc9e85</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c0712131-2da9-4842-b4d9-9d918f31e1d8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2f956392-ce5a-4aa6-b4cb-d7d9de89d654</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aa897937-ce3c-4e77-8206-0cad741f0d38</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a966d7fc-5f01-4fdf-8c15-668a2712c065</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/CONSUMER/SPACETIME/Checkout Scenarios/Checkout by Unit and Duration/14_ServicePerMonthNot247</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5d242fc1-fa65-404e-8d62-3c1092efdded</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e4f57d01-f413-4e84-8cff-cf342d74eeec</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2ce57506-d659-4d8b-98e3-1cd92e3f0d5f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>579de461-e43b-46db-88e7-d24a26817ada</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>df019672-61f2-4033-9af2-94c78499956d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>78590356-7a55-42fb-8710-adc7fb4a7a1c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5d2bce0e-aada-4263-a44b-763a8fbcfc94</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4492e525-c610-435f-81d5-1ff1e7a938d9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/CONSUMER/SPACETIME/Checkout Scenarios/Checkout by Unit and Duration/15_ServiceCustomPer15minNot247</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>76372617-b801-4935-927b-d334ed07d783</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>130308f7-3b2a-45f3-b8cb-145b947d5909</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7381fde9-3455-4cb9-96e7-4987b4727611</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>31d9920a-a2d1-4d32-9b07-b37a784c08a4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6e3cb46c-3160-4bba-ac70-bc2c41fad12e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>31f05f50-edb6-46e9-8466-afee0b33b7bf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d6b26777-d3c7-4565-9787-9f5776ce0f05</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>24768f6e-718f-4511-a96e-b27cdfdf9a09</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/CONSUMER/SPACETIME/Checkout Scenarios/Checkout by Unit and Duration/16_ServiceCustomPer150minNot247</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ba09cbda-78e1-46dc-a9b2-fb3cd669e488</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c4aa77c9-9d7a-4747-9bda-7fb035bcf10f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a6d22b01-728d-4f47-b37e-5a9d65b21094</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a55d727e-6ec1-4174-b78b-89cf5ba52dc8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>443a18f5-b60e-440a-9e48-053d3a5741a4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4738299c-f98f-4e7a-b3f8-3a6a3836490e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6f0e7b4e-6775-4508-a84f-074b5b079581</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fd9a404e-b54d-4db9-be4b-bf2e985024cc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/CONSUMER/SPACETIME/Checkout Scenarios/Checkout by Unit and Duration/17_ServiceCustomPer1hourNot247</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ca4ffe5b-9f0f-439a-8cf0-a897a7baa06f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6bfc50a3-c8ab-4524-a873-3f18a26c4382</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5c013c1e-15fe-48e2-9538-46a6baf9452c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>33e946e9-caec-458b-b6c9-c914ee61a40f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>70525540-ace8-4c3c-8fc6-b6b51ff96e3b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a6ff055f-aead-44e1-8126-06ee2e1e13a5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f4c65d31-e732-4813-89ed-3b2603e08eed</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4b956ee7-7b9e-47ae-af3d-d6c3272e36eb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/CONSUMER/SPACETIME/Checkout Scenarios/Checkout by Unit and Duration/18_ServiceCustomPer1DayNot247</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>206a3ff0-6761-41c8-bef3-0bcd6f30d2d5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>760abf0b-4c12-4c07-a7e6-fd349f5b2ae3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>124e8b1b-eca4-4584-9b41-3e4081430d32</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1ed889f0-1108-4727-a370-96625e282278</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e98c67ec-7fbf-4fdd-b0b4-62537976fdfe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eefe227e-2858-4957-a49c-4caee1aee807</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e1ae74dc-1ef7-47d6-8a80-04f56f907511</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2b33ca1a-5b55-4af0-9196-758f28aa7df1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/CONSUMER/SPACETIME/Checkout Scenarios/Checkout by Unit and Duration/19_ServiceOvernight</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>841b4652-8031-4d15-8127-ba869baef800</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3b631dc8-7d8b-4e17-b295-2bd3a43f0a75</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2dc6dbf6-7c14-42c2-9496-58e722aebbbc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>579fa2cf-12b7-44a3-a6aa-3fb9fdefefad</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6be2741e-cef8-4192-be83-abf44e162318</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6badcd1a-b0e7-4c60-8343-156e934a0ae2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a43d4d3a-c9ce-4bcc-bf98-82d2fd168730</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c47fc8d9-4ca5-4787-8008-746ec1e284c7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/CONSUMER/SPACETIME/Checkout Scenarios/Checkout by Unit and Duration/20_ServiceOvernighPerWeek</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94ad1ce2-b489-4eed-b708-178c098011a0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c10dcffd-13f9-457c-af99-b377cd401e8f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a778ba46-c8f1-43b0-94c8-888913dd58fc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6e160f92-b84a-4201-9aea-2624f3740101</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>270a16ac-17bd-4c78-bc38-3926348d7d58</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a2a111d5-be03-4b30-9264-ec09c46a1261</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1e2678ed-77bd-46b9-b831-48a778381257</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9602716d-4417-4f9f-85a7-4d1900b1de10</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/CONSUMER/SPACETIME/Checkout Scenarios/Checkout by Unit and Duration/21_ServiceOvernightPerMonth</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e2149362-f6f8-4a2a-87db-83b3989a6f48</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8655942d-3615-4f4a-94e3-73675e9d7a01</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>145881d7-2a1e-4f7a-94fc-6f32a486c487</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1faa2064-028a-4211-aed0-31ff07c59e17</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9703666c-ccd2-41c1-a910-8e3e26239043</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cfe24c31-baac-4c7a-8444-60873fc0e806</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>23b7a7e5-8e98-43ee-80ae-25f9b9b3ad4d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7da5289d-fcf8-477b-993d-302043d979ec</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/CONSUMER/SPACETIME/Checkout Scenarios/Checkout by Unit and Duration/22_ServiceOvernightPer1Night</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d5c4509-c497-4d7a-be3b-b292dda70fc6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5181f133-e1c2-4f4f-8902-13d136565016</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>33786422-5af7-40db-a8ad-9359d5fd80c6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5b2ff090-94e6-410c-a78d-f61bd196d30f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>13d73c6a-0ce2-4ad0-b1d0-143bdacf6407</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dd6d2d9c-452a-4926-a371-cc78bfebf0ec</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1c2919c3-8a40-487e-9a4f-74a6444d9f58</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>13c63057-db97-4829-8e8d-47f7555fb023</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/CONSUMER/SPACETIME/Checkout Scenarios/Checkout by Unit and Duration/23_ServiceOvernightPer28Nights</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2093be5d-6e3d-43bc-bcf3-df71d090140a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dd94d19a-f7aa-4d0b-9d8f-6760239657fb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5d9414d5-ea93-497f-835d-7fc51e208550</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e0dc829d-15dd-4ca0-841c-ef9936144f98</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c6d251a2-e242-4737-ac1f-e514b1402d9c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c1843855-0bc2-4ae4-a75d-ce7bb3f2b457</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7c4c7702-1c18-4355-8df7-72f116e174de</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e2625f61-d578-4a9e-be02-46ae8736b27d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Utilities/MERCHANT/Logout</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
