<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select New Language</name>
   <tag></tag>
   <elementGuidId>e5e06932-ead2-4ed4-b1d1-9db21aa1052e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select[@id = 'drpLanguage']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[3]/div[2]/div[2]/div/div[1]/div[2]/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>drpLanguage</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Select New Language
                                    Afrikaans
                                    Albanian
                                    Arabic
                                    Armenian
                                    Azerbaijani
                                    Basque
                                    Belarusian
                                    Bengali
                                    Bosnian
                                    Bulgarian
                                    Catalan
                                    Cebuano
                                    Chichewa
                                    Chinese (Simplified)
                                    Chinese (Traditional)
                                    Croatian
                                    Czech
                                    Danish
                                    Dutch
                                    English
                                    Esperanto
                                    Estonian
                                    Filipino
                                    Finnish
                                    French
                                    Galician
                                    Georgian
                                    German
                                    Greek
                                    Gujarati
                                    Haitian Creole
                                    Hausa
                                    Hebrew
                                    Hindi
                                    Hmong
                                    Hungarian
                                    Icelandic
                                    Igbo
                                    Indonesian
                                    Irish
                                    Italian
                                    Japanese
                                    Javanese
                                    Kannada
                                    Kazakh
                                    Khmer
                                    Korean
                                    Lao
                                    Latin
                                    Latvian
                                    Lithuanian
                                    Macedonian
                                    Malagasy
                                    Malay
                                    Malayalam
                                    Maltese
                                    Maori
                                    Marathi
                                    Mongolian
                                    Myanmar (Burmese)
                                    Nepali
                                    Norwegian
                                    Persian
                                    Polish
                                    Portuguese
                                    Punjabi
                                    Romanian
                                    Russian
                                    Serbian
                                    Sesotho
                                    Sinhala
                                    Slovak
                                    Slovenian
                                    Somali
                                    Spanish
                                    Sudanese
                                    Swahili
                                    Swedish
                                    Tajik
                                    Tamil
                                    Telugu
                                    Thai
                                    Turkish
                                    Ukrainian
                                    Urdu
                                    Uzbek
                                    Vietnamese
                                    Welsh
                                    Yiddish
                                    Yoruba
                                    Zulu

                    </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;drpLanguage&quot;)</value>
   </webElementProperties>
</WebElementEntity>
