<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Duration</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>f534273d-3fe3-483b-a014-6f50e83ec0ff</testSuiteGuid>
   <testCaseLink>
      <guid>f692cd41-ae23-4892-a787-cdb488b351b9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CONSUMER/SPACETIME/Checkout Scenarios/Merchant Level Comission/In Range/Duration/01_ServicePerHour247</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>27790a59-9fe7-4aa0-ad54-3b780e7a103d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ac89b83d-4a4e-4228-93ab-3dddad0ff5cb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7a118ae4-101b-4ba7-8f85-a7cf48bb7bcc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>04ecf138-c2fd-4985-81b7-5ca34d504b33</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d4708fe-db83-4aa5-92d0-7045c7f85633</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f7dea2f0-a522-4e58-ae0e-d3c1d8c6200f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>921a0619-7707-4585-b0c6-c2e7f1054c1b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>61c10889-a042-4c72-bebc-3cec58968153</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0727fc70-6fa9-4444-804b-ec6f66b160f7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CONSUMER/SPACETIME/Checkout Scenarios/Merchant Level Comission/In Range/Duration/02_ServiceCustomPer15min247</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7a853dd1-31b9-4f87-a880-29656b29588a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>41c44989-47d1-43f0-8130-58c7729de253</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>82fdbae9-5d6f-4c54-ade5-f2f272a87f78</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>66eee0e0-cc66-4964-ba0e-b787e804b472</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>29def2a6-27b4-42f1-87e5-452ecd7ebf25</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b81bc587-c57c-4fc1-93b1-8f716750d03f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c5d5534f-4cde-4046-8aae-f0234c996749</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fb1bd647-895c-4ae1-9ec7-bbedcd2c4d57</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CONSUMER/SPACETIME/Checkout Scenarios/Merchant Level Comission/In Range/Duration/03_ServicePerHourNot247</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0c0b8130-4b03-4e22-bc83-6e9f8752182e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bc9d8b00-a72b-4d50-a3fd-e0c099ccd75d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3bd76bb5-3d1d-4ba6-b2b6-f3d3e8492800</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>665acd6f-1d05-4654-a667-fe9a8bec3815</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>42a18267-f0e4-4ec8-9d0f-4465d6567e5d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>517f7c01-4e7a-48f4-9e65-917f0011bfcc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c6d2e56d-5891-4d94-b2ab-7d46825caf21</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>388162ac-f657-4e99-af94-9a678e9aced2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CONSUMER/SPACETIME/Checkout Scenarios/Merchant Level Comission/In Range/Duration/04_ServiceOvernightPerMonth</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>22c950e2-d0e9-4b01-adc3-60607d002c5b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>433d9049-f577-404b-8441-5cd737098a9a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4e81f096-a6f9-4497-bef8-6bf6bd7907a2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fcf8fc0d-2552-4166-a0bf-0f84a3ec2d12</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a2871769-674f-447d-8821-dfcab0061989</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6ff95fc0-510a-4dbd-867b-e30e4149c98f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>06fb0028-24bf-40f3-8aa3-61965d8a93e1</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
