<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>02_SearchResultPage</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>16ab5e36-14b0-4a37-ab5b-12c0ad4f17ae</testSuiteGuid>
   <testCaseLink>
      <guid>bbdc3c6c-9c0d-414c-8ff4-887d659b90ae</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Utilities/CONSUMER/Consumer Login Non Private</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>b157f555-b4cf-41dd-963e-488a797b2ae4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CONSUMER/BESPOKE/Search Result Page/Search per Page/Search Results Page/a_NavigateToSearchResultPage</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>9b25bba4-f6a3-41e0-81e3-8f5c24bed8ce</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/CONSUMER/BESPOKE/Search/SearchPerPage</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>9b25bba4-f6a3-41e0-81e3-8f5c24bed8ce</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>itemName</value>
         <variableId>a1f7b832-52c5-42b8-a49b-93917a871925</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>00da9069-a15d-4187-b396-882831404507</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CONSUMER/BESPOKE/Search Result Page/Search per Page/Search Results Page/01_searchItemName</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>5d9cd114-ebd9-4c2d-bcbe-6100984f2815</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/CONSUMER/BESPOKE/Search/SearchPerPage</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>5d9cd114-ebd9-4c2d-bcbe-6100984f2815</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>itemName</value>
         <variableId>7ac7f009-e6ce-46c3-b57b-eaa8b0c4513f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2433595b-6055-4ae1-8d7d-5fce4d0aca7b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CONSUMER/BESPOKE/Search Result Page/Search per Page/Search Results Page/02_searchItemDescription</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>83bc7170-dbd5-4255-a08b-b761e3cfb458</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/CONSUMER/BESPOKE/Search/SearchPerPage</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>83bc7170-dbd5-4255-a08b-b761e3cfb458</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>itemDescription</value>
         <variableId>7fda0fde-d549-4da9-9965-97b934950794</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>83bc7170-dbd5-4255-a08b-b761e3cfb458</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>itemName</value>
         <variableId>15f8f6cb-744d-4cf7-b509-ed1a41ad86e7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fe6472bb-3273-4847-9fbc-8af383545457</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CONSUMER/BESPOKE/Search Result Page/Search per Page/Search Results Page/03_searchPartialItemName</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>eb563b62-0f38-41b7-9d44-8b6569fa3f5b</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/CONSUMER/BESPOKE/Search/SearchPerPage</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>eb563b62-0f38-41b7-9d44-8b6569fa3f5b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>itemNamePartial</value>
         <variableId>ffa7818d-c8ed-40d4-9926-1cfdfc9101d9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>eb563b62-0f38-41b7-9d44-8b6569fa3f5b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>itemName</value>
         <variableId>f38b97d8-2a44-4f1e-87a9-c5b658c9c4c3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>acd1c889-6c58-4413-adfa-dd61195c9b1b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CONSUMER/BESPOKE/Search Result Page/Search per Page/Search Results Page/04_searchPartialItemDescription</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>80957dff-eac6-42ef-8b32-526520572a4d</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/CONSUMER/BESPOKE/Search/SearchPerPage</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>80957dff-eac6-42ef-8b32-526520572a4d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>itemDescriptionPartial</value>
         <variableId>c7a86189-e746-44e9-a568-7d072b257b25</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>80957dff-eac6-42ef-8b32-526520572a4d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>itemName</value>
         <variableId>d2aba72d-d0ff-4c88-bf8b-43eb77200a74</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a0c02cb8-7db4-4829-89d9-d66a89712b0e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Utilities/MERCHANT/Logout</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
