<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textlabel_headerOrderStatus</name>
   <tag></tag>
   <elementGuidId>c465d69d-2dbf-480e-8579-745a849f8c28</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ordrhist-status-col</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ORDER STATUS</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react_0HLQLSHTL0UMH&quot;)/div[1]/div[@class=&quot;ordrhist-list-heading&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;ordrhist-list-tit-sec&quot;]/div[@class=&quot;ordrhist-status-col&quot;]</value>
   </webElementProperties>
</WebElementEntity>
