<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Deliuveryfrom_value</name>
   <tag></tag>
   <elementGuidId>5c8171d3-8e5f-4110-bb17-13a3531e4697</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Philippines</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MyPrintDiv&quot;)/div[@class=&quot;ordr-dtls-top-area&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;ordr-dtls-buyer-info delivert_detail&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;ordr-dtls-buyer-infoind col-md-3&quot;]/p[1]</value>
   </webElementProperties>
</WebElementEntity>
