<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Timestamp_value</name>
   <tag></tag>
   <elementGuidId>7aa4d8cb-cbb7-405b-a760-ad023a0ae17d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[4]/div[1]/div[1]/div/div[1]/div[2]/div[1]/div[1]/text()</value>
   </webElementProperties>
</WebElementEntity>
