<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textlabelvalue_PaymentType</name>
   <tag></tag>
   <elementGuidId>82552faa-7af8-4bed-a3f6-783b26ca9e71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[3]/div[2]/div[1]/div[2]/div/div[2]/div[1]/div[2]/div[1]/div[2]/p</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
