<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textlabevalue_SubTotal</name>
   <tag></tag>
   <elementGuidId>7448e96c-f4fd-400a-83ee-5da8658a69f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[3]/div[2]/div[1]/div[2]/div/div[2]/div[3]/div[2]/div[1]/div/div[3]/div[2]/p[1]/span[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
