<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>arrowdown_AvrOrderByRev</name>
   <tag></tag>
   <elementGuidId>214a6a10-e9e4-4656-a74a-903d9327c564</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react_0HM2IQGJ48CK9']/div/div/div/div/div[2]/ul/li[4]/div[2]/div[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[4]/div[2]/div/div/div/div/div[2]/ul/li[4]/div[2]/div[2][count(. | //*[@class = 'arrow-down']) = count(//*[@class = 'arrow-down'])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.average-rev > div.high-low.green > div.arrow-down</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>arrow-down</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div/div/div/div[2]/ul/li[4]/div[2]/div[2]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react_0HM2IQGJ48CK9']/div/div/div/div/div[2]/ul/li[4]/div[2]/div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/div[2]/div[2]</value>
   </webElementXpaths>
</WebElementEntity>
