<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_edit1st</name>
   <tag></tag>
   <elementGuidId>2ae3e22b-2267-4e9b-bbf0-275b667a8a6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[3]/div[2]/div/div[2]/div/div[2]/div/div[2]/ul/li[9]/div/div[7]/div/a[1]/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[3]/div[2]/div/div[2]/div/div[2]/div/div[2]/ul/li[9]/div/div[7]/div/a[1]/i</value>
   </webElementProperties>
</WebElementEntity>
