<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Duration</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>556465b7-e7df-4e06-8f7a-55047afed16e</testSuiteGuid>
   <testCaseLink>
      <guid>4698c400-8104-40e4-a651-e98cf68d96ae</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CONSUMER/SPACETIME/Chat Scenarios/Merchant Level Commission/In Range/Duration/01_ServicePerHour247</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>93501edd-e916-4b0b-8274-429d49f2bbf7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>493c68e0-7ee5-4fea-abe0-c8d7c76c5349</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bada8005-35fb-4e54-bffc-59027f3c5f95</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d1391aeb-ebd9-4d8d-a31f-4e2125437001</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>78fbeabb-1814-4cb3-9dd3-69667af57d88</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>795c31fd-3bfa-4bdf-8e64-49d75e0c5f1f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e6849de3-2f7f-4665-98c3-52478a5925fb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b6e1645-a03b-4ab9-b367-3f128575c874</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eb40cf0f-6065-4a5c-b814-0d939646b2b7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>27cf1ca3-cb49-49cb-906c-e3d312778f27</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6eb57c82-0071-4ded-9a2a-17ad1fbddfaa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c94cf90a-a280-4e42-8181-a00711a8f6b6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0e608b09-f7d0-4305-90a2-189855db3084</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CONSUMER/SPACETIME/Chat Scenarios/Merchant Level Commission/In Range/Duration/02_ServiceCustomPer15min247</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4fbbbb90-640d-41f2-ac55-c123f73a956d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>355c92c1-9096-4719-af1f-cd67458b7a29</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>29a188bf-6aeb-49dd-9f1b-a26cc6f9dd05</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2fc53830-a19f-4c0d-9620-4122cd6283d8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5aa92341-f86c-42bf-9cc5-93e572d68564</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f62fe924-6ebb-457c-8764-5f08e87b5357</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c68ba768-c801-4f3c-a3d9-1af26fe84a21</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1f4968a3-d205-4825-9c0a-82d9c8b1669d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dcad673c-8f5e-4eda-83a7-bbaa3d0e177c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bacfd481-f007-4479-91c2-687a88eba5d6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0f123f8a-53d1-4413-a834-ee3b4dd67d72</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9dd986a6-d016-4498-b05d-2ef2085d6384</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>169f2610-ae3b-4aea-a6d0-f9410d896bc8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CONSUMER/SPACETIME/Chat Scenarios/Merchant Level Commission/In Range/Duration/03_ServicePerHourNot247</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f14dd1a5-6024-4851-9ce1-3af0d0cbb343</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>641360f6-8b27-4f6e-9759-f7bd29a98c39</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e7ec87af-bad2-4df5-8849-1acb80505a37</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>40ff4377-fe9c-4232-b52a-791d19d5efcc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5052b3f9-88ec-4811-951d-00886cd8f2e6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>775c0b33-c263-409a-9ee4-00ee6d8f3deb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e3bc9e9d-61e7-4c2d-80aa-8016db913c92</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2e4566a4-551f-4483-99c1-0260787d3331</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b762868d-7959-47e1-9981-e15fa66b12d6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>09041376-294d-4e36-b0b0-57ccdabd0505</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3f904b26-cbb4-49ea-a483-f5fbca04cc26</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f250dd02-3719-4926-be29-a89f09210a19</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bf2a4655-b78b-4c99-9231-f56fef9bd1d9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CONSUMER/SPACETIME/Chat Scenarios/Merchant Level Commission/In Range/Duration/04_ServiceOvernightPerMonth</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0f241910-82ef-4272-926e-29f8f3aff5bf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d05b3f26-ddce-4723-b7ef-16005be671f5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8787f656-acbf-4b67-8d22-37b446b86edc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d3811d3f-4efc-4b84-91cb-40c986c26913</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>16d7b347-ed3b-4856-b489-53328900210c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>da9f9a30-8c17-4e74-acbc-1aea876b0bd6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>89065cda-116b-4907-9c1a-234e04be2a1b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c317e0d9-2fed-4fb8-b8e8-6f03f5d87f82</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6841afea-75ba-4570-9330-9743fc182f4d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d2e497c4-4cf8-451e-8a39-75ad49d55e91</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f6c456c2-ebf6-475a-9a8b-abca29ffd188</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>54c8b8f8-7524-408d-a0cf-b987b3153515</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
