<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Create Account</name>
   <tag></tag>
   <elementGuidId>4710f1dc-d5d0-4c4e-ae4a-602a71b85d6b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id=':mp']/div/div[2]/div/div/div/div[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://u2507958.ct.sendgrid.net/ls/click?upn=6c2JhZPIzQEETQwyPIEXqDzIJYXy2j67RHFR3-2BQl2-2FivfdyaTqyjvXhT4Qw2S8XmJVXNTkbVVcOl9MNN7pvIAt8zlyCmxJw2hyEwrqLcA6iH8G6JgMiK8IH2xjXfVrZykPckI-2BlBcnP2mRBy11Ygy-2BTFPDXyMwpEw0Hz7leOYr-2Bue-2BnCt8t6rjSH3gYJ3tXuudeF_-2Bnxlb9E0dkbRZjc0R-2BNtGlMx3WmfXXvVijOY2qF-2BM-2FjpMCcHFHbSWoyx5TcfawZMaTyUMyGA-2BWg5Fil9ANtKjtJSZnmgvYTWDBTk-2B-2F0K2CUAm2QUZ2rEu7bpnZ9gxIc0cxQpkXbYT80RxuHZJ7oFkUZxOO-2B4YKcxyyVS2gR1-2BA0xR2mN2kr8NuaxSWap70T3UcmbqgytRB0ZgAPAz-2FHl0KyOSNaGxuFyc5FgSZej2wI-3D</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-saferedirecturl</name>
      <type>Main</type>
      <value>https://www.google.com/url?q=https://u2507958.ct.sendgrid.net/ls/click?upn%3D6c2JhZPIzQEETQwyPIEXqDzIJYXy2j67RHFR3-2BQl2-2FivfdyaTqyjvXhT4Qw2S8XmJVXNTkbVVcOl9MNN7pvIAt8zlyCmxJw2hyEwrqLcA6iH8G6JgMiK8IH2xjXfVrZykPckI-2BlBcnP2mRBy11Ygy-2BTFPDXyMwpEw0Hz7leOYr-2Bue-2BnCt8t6rjSH3gYJ3tXuudeF_-2Bnxlb9E0dkbRZjc0R-2BNtGlMx3WmfXXvVijOY2qF-2BM-2FjpMCcHFHbSWoyx5TcfawZMaTyUMyGA-2BWg5Fil9ANtKjtJSZnmgvYTWDBTk-2B-2F0K2CUAm2QUZ2rEu7bpnZ9gxIc0cxQpkXbYT80RxuHZJ7oFkUZxOO-2B4YKcxyyVS2gR1-2BA0xR2mN2kr8NuaxSWap70T3UcmbqgytRB0ZgAPAz-2FHl0KyOSNaGxuFyc5FgSZej2wI-3D&amp;source=gmail&amp;ust=1601536332398000&amp;usg=AFQjCNFNl7bQMcFcuagVJeRaR8W4u-Uy_Q</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create Account</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:mp&quot;)/div[@class=&quot;HOEnZb&quot;]/div[@class=&quot;im&quot;]/div[1]/div[1]/div[1]/div[3]/a[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id=':mp']/div/div[2]/div/div/div/div[3]/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Create Account')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='qadianne@gmail.com'])[3]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='me'])[1]/following::a[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reply'])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forward'])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Create Account']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://u2507958.ct.sendgrid.net/ls/click?upn=6c2JhZPIzQEETQwyPIEXqDzIJYXy2j67RHFR3-2BQl2-2FivfdyaTqyjvXhT4Qw2S8XmJVXNTkbVVcOl9MNN7pvIAt8zlyCmxJw2hyEwrqLcA6iH8G6JgMiK8IH2xjXfVrZykPckI-2BlBcnP2mRBy11Ygy-2BTFPDXyMwpEw0Hz7leOYr-2Bue-2BnCt8t6rjSH3gYJ3tXuudeF_-2Bnxlb9E0dkbRZjc0R-2BNtGlMx3WmfXXvVijOY2qF-2BM-2FjpMCcHFHbSWoyx5TcfawZMaTyUMyGA-2BWg5Fil9ANtKjtJSZnmgvYTWDBTk-2B-2F0K2CUAm2QUZ2rEu7bpnZ9gxIc0cxQpkXbYT80RxuHZJ7oFkUZxOO-2B4YKcxyyVS2gR1-2BA0xR2mN2kr8NuaxSWap70T3UcmbqgytRB0ZgAPAz-2FHl0KyOSNaGxuFyc5FgSZej2wI-3D')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[3]/a</value>
   </webElementXpaths>
</WebElementEntity>
