<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>value_Admin_Hyperlink_ConsMer_No</name>
   <tag></tag>
   <elementGuidId>72c6afe2-61b6-4090-abd4-cb0bfbd561b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;userDetailContainer&quot;)/div[@class=&quot;wrap-panel&quot;]/div[@class=&quot;custom-user-field-sec&quot;]/ul[@class=&quot;w-list-items&quot;]/li[22]/p[1]/img[@class=&quot;img-responsive imgpreview&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='userDetailContainer']/div[4]/div/ul/li[22]/p/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://0511bpdiana.test.arcadier.io/images/user/image-166042-637563985369376964-p2l7sl0699c32aa644fe9f011c65c2ff7088bf..jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-responsive imgpreview</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;userDetailContainer&quot;)/div[@class=&quot;wrap-panel&quot;]/div[@class=&quot;custom-user-field-sec&quot;]/ul[@class=&quot;w-list-items&quot;]/li[28]/a[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='userDetailContainer']/div[4]/div/ul/li[22]/p/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://0511bpdiana.test.arcadier.io/images/user/image-166042-637563985369376964-p2l7sl0699c32aa644fe9f011c65c2ff7088bf..jpg')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[22]/p/img</value>
   </webElementXpaths>
</WebElementEntity>
