<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textlabel_TotalValues</name>
   <tag></tag>
   <elementGuidId>bc9f2892-e692-471b-96a7-63c7e333f876</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chkout-totla-amt</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>THB ฿456.00</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;order-summary&quot;)/div[@class=&quot;checkout-payment-inner&quot;]/div[@class=&quot;checkout-itm-total-sec&quot;]/div[@class=&quot;check-total-btm-sec&quot;]/div[@class=&quot;chkout-totla-amt&quot;]</value>
   </webElementProperties>
</WebElementEntity>
