<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textlabel_unitPriceTo</name>
   <tag></tag>
   <elementGuidId>dd9b5374-4183-4564-a6f3-0f0f34b3c4c6</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>filter-price-label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>฿</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react_0HLQLTOH1T223&quot;)/div[1]/div[@class=&quot;wrapper-section&quot;]/div[@class=&quot;filter-content-section&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;filter-applied-value&quot;]/div[@class=&quot;filter-row&quot;]/span[@class=&quot;filter-price-label&quot;]</value>
   </webElementProperties>
</WebElementEntity>
