<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Inbox</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>6cee1231-5161-48e4-af0a-ad4e1db5c160</testSuiteGuid>
   <testCaseLink>
      <guid>6f1efe7b-e1ae-481b-88c7-e41bd682d06b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Utilities/CONSUMER/Consumer Login Non Private</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>e262085e-fec5-4827-9c60-6611477d9ed3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CONSUMER/SPACETIME/Search Scenario/Keyword/Inbox/a_NavigateToInbox</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>f904ca08-850e-42c5-831f-f242888e89b9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CONSUMER/SPACETIME/Search Scenario/Keyword/Inbox/01_searchItemName</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a0b41b3a-abc9-4363-b356-ab02b7c2aef5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>887fc746-ae0d-4ed2-961b-1b310a933b40</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CONSUMER/SPACETIME/Search Scenario/Keyword/Inbox/02_searchItemDescription</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>60aa4620-ca90-4566-af3a-d10e5ec33233</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>48fec4ef-5c71-4415-ab23-a1f5c4e60858</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cc351702-8490-433d-9838-df37023de5f9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CONSUMER/SPACETIME/Search Scenario/Keyword/Inbox/03_searchPartialItemName</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ac9b857f-4859-494b-95fc-1489caf59d2f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d6f9c23b-390c-4dc9-a1b0-02ea9474fb2b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a380fa5e-7949-4a91-acbc-73c711a6347e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CONSUMER/SPACETIME/Search Scenario/Keyword/Inbox/04_searchPartialItemDescription</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1fd4d668-566b-4dab-bbfb-e0ae127f29d5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2cd76c3e-0e85-47fe-895f-1e8ed70551da</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>97b6b0ea-9f71-4ff3-b2fb-daa937eb7cef</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CONSUMER/SPACETIME/Search Scenario/Keyword/Inbox/05_BlankSearch</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4a48ef45-51be-4374-acab-641573f0fe8f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cb35b6f0-6f6b-4bc3-bb98-b2089d30f91b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Utilities/MERCHANT/Logout</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
