<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Contact_Email</name>
   <tag></tag>
   <elementGuidId>c7be26bd-afbb-4234-9470-79f3753b93da</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>mailto:arcadierteam@gmail.com</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>arcadierteam@gmail.com</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react_TuCFohtY5EG2PnGWVmfhYQ&quot;)/div[@class=&quot;main&quot;]/div[@class=&quot;container-success&quot;]/div[@class=&quot;content-box content-center box2&quot;]/div[@class=&quot;content-box-shadow&quot;]/p[1]/a[1]</value>
   </webElementProperties>
</WebElementEntity>
