<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>option_Stripes</name>
   <tag></tag>
   <elementGuidId>3fbb9c07-1ab6-45ba-9fba-e69dc78f5dc2</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tag fa fa-bars</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>variantid</name>
      <type>Main</type>
      <value>23672</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Stripes</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add-item-variant-area&quot;)/div[@class=&quot;box-shadow&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;item-form-group&quot;]/div[@class=&quot;variants-section&quot;]/div[@class=&quot;col-sm-12&quot;]/div[@class=&quot;options-draw&quot;]/div[@class=&quot;add-options-table&quot;]/div[@class=&quot;options-header&quot;]/div[@class=&quot;options-body ui-sortable&quot;]/div[@class=&quot;options-row&quot;]/div[@class=&quot;options-cell option-choices&quot;]/div[@class=&quot;bootstrap-tagsinput ui-sortable&quot;]/span[@class=&quot;tag fa fa-bars&quot;]</value>
   </webElementProperties>
</WebElementEntity>
