<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown_Card</name>
   <tag></tag>
   <elementGuidId>9fbc3105-ac31-4e4f-86e8-7bb6ffb4ba5b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[1]/div[1]/div/div[2]/div[1]/div[2]/div/div/div[1]/div[1]/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[1]/div[1]/div/div[2]/div[1]/div[2]/div/div/div[1]/div[1]/div[2]/div</value>
   </webElementProperties>
</WebElementEntity>
