<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>basic_CustomJavascriptEditor</name>
   <tag></tag>
   <elementGuidId>dadd1cc3-5e03-4526-b59e-ee3cff94b0af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#period-day > div.subs-layer.subs-three-layer.Basic > div.subs-layer-bottom > ul.subs-list-container > li.strikethrough</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='period-day']/div/div[3]/ul/li[7]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>strikethrough</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Custom Javascript editor</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;period-day&quot;)/div[@class=&quot;subs-layer subs-three-layer Basic&quot;]/div[@class=&quot;subs-layer-bottom&quot;]/ul[@class=&quot;subs-list-container&quot;]/li[@class=&quot;strikethrough&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='period-day']/div/div[3]/ul/li[7]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Custom Code Input(HTML,CSS)'])[7]/following::li[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Plug-in Marketplace Access'])[7]/preceding::li[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/div[3]/ul/li[7]</value>
   </webElementXpaths>
</WebElementEntity>
