<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dd_category</name>
   <tag></tag>
   <elementGuidId>5205abf4-651a-4384-9db8-c436ee53cfcf</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select AllCategory 01Category 02Category 2.1Category 2.2Category 03Category 3.1Category 3.1.1Category 3.1.2Category 3.2Category 04Category 4.1Category 4.2Category 4.3Category 4.4Category 4.5Category 4.6Category 4.7Category 4.8Category 4.9Category 4.10Category 4.11Category 4.12Category 4.13Category 4.14Category 4.15Category 4.16Category 4.17Category 4.18Category 4.19Category 4.20Category 05Category 5.1Category 5.1.1Category 5.1.2Category 5.1.3Category 5.1.4Category 5.1.5Category 5.1.6Category 5.1.7Category 5.1.8Category 5.1.9Category 5.1.10Category 5.1.11Category 5.1.12Category 5.1.13Category 5.1.14Category 5.1.15Category 5.1.16Category 5.1.17Category 5.1.18Category 5.1.19Category 5.1.20Category 5.2Category 06Category 6.1Category 6.1.1Category 6.1.1.1Category 6.1.1.1.1Category 6.1.1.1.1.1Category 6.1.1.1.1.1.1Category 6.1.1.1.1.1.1.1Category 6.1.1.1.1.1.1.1.1Category 0%Category 1%Category 99%Category 100%Category 11Category 12Category 13Category 14Category 15Category 16Category 17Category 18Category 19Category 20Category Name mAx 021!!@#$%^&amp;!Category For Editcategory 1Category 2</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react_0HM0HOH4IG40D&quot;)/div[@class=&quot;filter-bar page-topnav&quot;]/form[@class=&quot;form-inline form-filter&quot;]/div[@class=&quot;sassy-filter lg-filter&quot;]/div[@class=&quot;sassy-flex&quot;]/div[@class=&quot;sassy-l grey_filter&quot;]/div[1]/div[@class=&quot;group-search&quot;]/div[@class=&quot;group-search-flex&quot;]/span[@class=&quot;select-sassy-wrapper&quot;]/div[@class=&quot;advanced-select&quot;]/div[@class=&quot;dropdown&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react_0HM0HOH4IG40D']/div/form/div/div/div/div/div/div/span[3]/div/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trisha Aira'])[1]/following::div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='seller'])[2]/following::div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[3]/div/div</value>
   </webElementXpaths>
</WebElementEntity>
