<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>25_checkboxUserGroups</name>
   <tag></tag>
   <elementGuidId>b6fbfaee-65d7-4f0c-b826-724a7e9c8271</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[3]/div[2]/div/div[3]/div/div[4]/div/table/tbody/tr[27]/td[2]/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
