<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>41_checkboxThemes</name>
   <tag></tag>
   <elementGuidId>b9cc45ee-6047-4901-9c4e-921bdbf350b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[3]/div[2]/div/div[3]/div/div[4]/div/table/tbody/tr[45]/td[2]/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
