<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>37_checkboxCustomCodes</name>
   <tag></tag>
   <elementGuidId>6ad8958e-040f-4f3a-a783-ffb05af8ebc3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[3]/div[2]/div/div[3]/div/div[4]/div/table/tbody/tr[46]/td[4]/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
